### Post: create candidate
POST http://localhost:8080/candidate/
Content-Type: application/json

{
  "username": "b.dev",
  "name": "b",
  "email": "b@email.com",
  "password": "12345678910",
  "description": "Desenvolvedor Java",
  "curriculum": "a"
}

### Post: create company
POST http://localhost:8080/company/
Content-Type: application/json

{
  "username": "java_jobs",
  "name": "Java Jobs",
  "password": "987@654@321",
  "email": "java@jobs.com.br",
  "description": "Empresa responsável por gerenciar vagas para desenvolvedores Java",
  "website": "http://www.java-jobs.com.br"
}

### 

POST http://localhost:8080/auth/company/
Content-Type: application/json 

{
  "username": "java_jobs",
  "password": "987@654@321",
}

### Post: create job
POST http://localhost:8080/job/
Content-Type: application/json
Authorization: Bearer {660D366FCB7B710A6C134FD844460892}

{
  "description": "Vaga para desenvolvedor Java que deseja trabalhar com Spring Boot",
  "benefits": "GymPass, Plano de Saúde, folga no aniversário, Vale Alimentação e Refeição",
  "level": "JUNIOR",
}