### Post: create candidate
POST http://localhost:8080/candidate/
Content-Type: application/json

{
  "username": "eduardo.dev",
  "name": "Eduardo",
  "email": "Eduardo@email.com",
  "password": "1234@1234@1234",
  "description": "Desenvolvedor Java",
  "curriculum": "c"
}

### Post: candidate auth
POST http://localhost:8080/candidate/auth
Content-Type: application/json

{
  "username": "eduardo.dev",
  "password": "1234@1234@1234"
}

### Get: 
GET http://localhost:8080/candidate/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqYXZhZ2FzIiwic3ViIjoiYmNjZmY2YzItNjMzOC00MTQzLWE1ZTUtOWM5NGQzYWMyMjM5Iiwicm9sZXMiOlsiY2FuZGlkYXRlIl0sImV4cCI6MTY5OTU4MTE5OX0.N34aVbNLFkaoYJS4ho2Lc8ZqrJNXy09elhYJOr6bt9Q

### Post: create company
POST http://localhost:8080/company/
Content-Type: application/json

{
  "username": "java_jobs",
  "name": "Java Jobs",
  "password": "987@654@321",
  "email": "java@jobs.com.br",
  "description": "Empresa responsável por gerenciar vagas para desenvolvedores Java",
  "website": "http://www.java-jobs.com.br"
}

### company auth

POST http://localhost:8080/company/auth
Content-Type: application/json 

{
  "username": "java_jobs",
  "password": "987@654@321"
}

### Post: create job
POST http://localhost:8080/job/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqYXZhZ2FzIiwiZXhwIjoxNjk5NTcwNTMyLCJzdWIiOiIzYzI4ZjI2Mi0zYTMyLTRhYjAtYmNhYS00NzQ1YTM1MDk0MDgifQ.Q2Pi7urz9wJrb5V4Ce4GK7KJ6Qmg_DAV48Paa678BOc

{
  "description": "Vaga para desenvolvedor Java que deseja trabalhar com Spring Boot",
  "benefits": "GymPass, Plano de Saúde, folga no aniversário, Vale Alimentação e Refeição",
  "level": "JUNIOR"
}